// <auto-generated />
using Khudmadad_Backend.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Khudmadad_Backend.Migrations
{
    [DbContext(typeof(Ef_DataContext))]
    [Migration("20221121142348_UserNumber")]
    partial class UserNumber
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Khudmadad_Backend.EfCore.Gig", b =>
                {
                    b.Property<int>("gigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("gigId"));

                    b.Property<int>("creatorId")
                        .HasColumnType("integer");

                    b.Property<string>("deadline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("pay")
                        .HasColumnType("double precision");

                    b.HasKey("gigId");

                    b.HasIndex("creatorId");

                    b.ToTable("Gig");
                });

            modelBuilder.Entity("Khudmadad_Backend.Efcore.Offers", b =>
                {
                    b.Property<int>("gigId")
                        .HasColumnType("integer");

                    b.Property<int>("freelancerId")
                        .HasColumnType("integer");

                    b.Property<double>("pay")
                        .HasColumnType("double precision");

                    b.Property<bool>("status")
                        .HasColumnType("boolean");

                    b.HasKey("gigId", "freelancerId");

                    b.HasIndex("freelancerId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("Khudmadad_Backend.EfCore.Roles", b =>
                {
                    b.Property<int>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("roleId"));

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("roleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Khudmadad_Backend.EfCore.Users", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userId"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("dob")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("roleId")
                        .HasColumnType("integer");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("userId");

                    b.HasIndex("roleId");

                    b.HasIndex("userName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Khudmadad_Backend.EfCore.Gig", b =>
                {
                    b.HasOne("Khudmadad_Backend.EfCore.Users", "Creator")
                        .WithMany("gig")
                        .HasForeignKey("creatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Khudmadad_Backend.Efcore.Offers", b =>
                {
                    b.HasOne("Khudmadad_Backend.EfCore.Users", "freelancer")
                        .WithMany("offer")
                        .HasForeignKey("freelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Khudmadad_Backend.EfCore.Gig", "gig")
                        .WithMany("offer")
                        .HasForeignKey("gigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("freelancer");

                    b.Navigation("gig");
                });

            modelBuilder.Entity("Khudmadad_Backend.EfCore.Users", b =>
                {
                    b.HasOne("Khudmadad_Backend.EfCore.Roles", "Role")
                        .WithMany("users")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Khudmadad_Backend.EfCore.Gig", b =>
                {
                    b.Navigation("offer");
                });

            modelBuilder.Entity("Khudmadad_Backend.EfCore.Roles", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("Khudmadad_Backend.EfCore.Users", b =>
                {
                    b.Navigation("gig");

                    b.Navigation("offer");
                });
#pragma warning restore 612, 618
        }
    }
}
